import {
  UpCircleTwoTone, DownCircleTwoTone, LeftCircleTwoTone,
  RightCircleTwoTone, PlayCircleTwoTone,
  QuestionCircleTwoTone, PlusCircleTwoTone,
  PauseCircleTwoTone, MinusSquareTwoTone,
  PlusSquareTwoTone, InfoCircleTwoTone,
  ExclamationCircleTwoTone, CloseCircleTwoTone,
  CloseSquareTwoTone, CheckCircleTwoTone, CheckSquareTwoTone,
  ClockCircleTwoTone, WarningTwoTone, StopTwoTone, EditTwoTone,
  CopyTwoTone, DeleteTwoTone, SnippetsTwoTone, DiffTwoTone,
  HighlightTwoTone, PieChartTwoTone, BoxPlotTwoTone, FundTwoTone,
  SlidersTwoTone, Html5TwoTone, MinusCircleTwoTone, AccountBookTwoTone,
  AlertTwoTone, ApiTwoTone, AppstoreTwoTone, AudioTwoTone, BankTwoTone, BellTwoTone,
  BookTwoTone, BugTwoTone, BuildTwoTone, BulbTwoTone, CalculatorTwoTone, CalendarTwoTone,
  CameraTwoTone, CarTwoTone, CarryOutTwoTone, CiCircleTwoTone, CiTwoTone, CloudTwoTone,
  CodeTwoTone, CompassTwoTone, ContactsTwoTone, ContainerTwoTone, ControlTwoTone,
  CopyrightTwoTone, CreditCardTwoTone, CrownTwoTone, CustomerServiceTwoTone,
  DashboardTwoTone, DatabaseTwoTone, DislikeTwoTone,
  DollarTwoTone, FastBackwardFilled,
  EnvironmentTwoTone,
  EuroCircleTwoTone,
  EuroTwoTone,
  ExperimentTwoTone,
  EyeTwoTone,
  EyeInvisibleTwoTone,
  FileAddTwoTone,
  FileExcelTwoTone,
  FileExclamationTwoTone,
  FileTwoTone,
  FileImageTwoTone,
  FileMarkdownTwoTone,
  FilePdfTwoTone,
  FilePptTwoTone,
  FileTextTwoTone,
  FileUnknownTwoTone,
  FileWordTwoTone, FolderOpenTwoTone


} from "@ant-design/icons";

export const StorageHouse = () => {
  return {
    "UpCircleTwoTone": <UpCircleTwoTone/>,
    "DownCircleTwoTone": <DownCircleTwoTone/>,
    "LeftCircleTwoTone": <LeftCircleTwoTone/>,
    "RightCircleTwoTone": <RightCircleTwoTone/>,
    "PlayCircleTwoTone": <PlayCircleTwoTone/>,
    "QuestionCircleTwoTone": <QuestionCircleTwoTone/>,
    "PlusCircleTwoTone": <PlusCircleTwoTone/>,
    "PauseCircleTwoTone": <PauseCircleTwoTone/>,
    "MinusCircleTwoTone": <MinusCircleTwoTone/>,
    "PlusSquareTwoTone": <PlusSquareTwoTone/>,
    "MinusSquareTwoTone": <MinusSquareTwoTone/>,
    "InfoCircleTwoTone": <InfoCircleTwoTone/>,
    "ExclamationCircleTwoTone": <ExclamationCircleTwoTone/>,
    "CloseCircleTwoTone": <CloseCircleTwoTone/>,
    "CloseSquareTwoTone": <CloseSquareTwoTone/>,
    "CheckCircleTwoTone": <CheckCircleTwoTone/>,
    "CheckSquareTwoTone": <CheckSquareTwoTone/>,
    "ClockCircleTwoTone": <ClockCircleTwoTone/>,
    "WarningTwoTone": <WarningTwoTone/>,
    "StopTwoTone": <StopTwoTone/>,
    "EditTwoTone": <EditTwoTone/>,
    "CopyTwoTone": <CopyTwoTone/>,
    "DeleteTwoTone": <DeleteTwoTone/>,
    "SnippetsTwoTone": <SnippetsTwoTone/>,
    "DiffTwoTone": <DiffTwoTone/>,
    "HighlightTwoTone": <HighlightTwoTone/>,
    "PieChartTwoTone": <PieChartTwoTone/>,
    "BoxPlotTwoTone": <BoxPlotTwoTone/>,
    "FundTwoTone": <FundTwoTone/>,
    "SlidersTwoTone": <SlidersTwoTone/>,
    "Html5TwoTone": <Html5TwoTone/>,
    "AccountBookTwoTone": <AccountBookTwoTone/>,
    "<AlertTwoTone />": <AlertTwoTone/>,
    "ApiTwoTone": <ApiTwoTone/>,
    "AppstoreTwoTone": <AppstoreTwoTone/>,
    "AudioTwoTone": <AudioTwoTone/>,
    "BankTwoTone": <BankTwoTone/>,
    "BellTwoTone": <BellTwoTone/>,
    "BookTwoTone": <BookTwoTone/>,
    "BugTwoTone": <BugTwoTone/>,
    "BuildTwoTone": <BuildTwoTone/>,
    "BulbTwoTone": <BulbTwoTone/>,
    "CalculatorTwoTone": <CalculatorTwoTone/>,
    "CalendarTwoTone": <CalendarTwoTone/>,
    "CameraTwoTone": <CameraTwoTone/>,
    "CarTwoTone": <CarTwoTone/>,
    "CarryOutTwoTone": <CarryOutTwoTone/>,
    "CiCircleTwoTone": <CiCircleTwoTone/>,
    "CiTwoTone": <CiTwoTone/>,
    "CloudTwoTone": <CloudTwoTone/>,
    "CodeTwoTone": <CodeTwoTone/>,
    "CompassTwoTone": <CompassTwoTone/>,
    "ContactsTwoTone": <ContactsTwoTone/>,
    "ContainerTwoTone": <ContainerTwoTone/>,
    "ControlTwoTone": <ControlTwoTone/>,
    "CopyrightTwoTone": <CopyrightTwoTone/>,
    "CreditCardTwoTone": <CreditCardTwoTone/>,
    "CrownTwoTone": <CrownTwoTone/>,
    "CustomerServiceTwoTone": <CustomerServiceTwoTone/>,
    "DashboardTwoTone": <DashboardTwoTone/>,
    "DatabaseTwoTone": <DatabaseTwoTone/>,
    "DislikeTwoTone": <DislikeTwoTone/>,
    "DollarTwoTone": <DollarTwoTone/>,
    "EnvironmentTwoTone": <EnvironmentTwoTone/>,
    "EuroCircleTwoTone": <EuroCircleTwoTone/>,
    "EuroTwoTone": <EuroTwoTone/>,
    "ExperimentTwoTone": <ExperimentTwoTone/>,
    "EyeTwoTone": <EyeTwoTone/>,
    "EyeInvisibleTwoTone": <EyeInvisibleTwoTone/>,
    "FileAddTwoTone": <FileAddTwoTone/>,
    "FileExcelTwoTone": <FileExcelTwoTone/>,
    "FileExclamationTwoTone": <FileExclamationTwoTone/>,
    "FileTwoTone": <FileTwoTone/>,
    "FileImageTwoTone": <FileImageTwoTone/>,
    "FileMarkdownTwoTone": <FileMarkdownTwoTone/>,
    "FilePdfTwoTone": <FilePdfTwoTone/>,
    "FilePptTwoTone": <FilePptTwoTone/>,
    "FileTextTwoTone": <FileTextTwoTone/>,
    "FileUnknownTwoTone": <FileUnknownTwoTone/>,
    "FileWordTwoTone": <FileWordTwoTone/>,
    "FolderOpenTwoTone": <FolderOpenTwoTone/>,
    "FastBackwardFilled": <FastBackwardFilled/>
  }
}













